package myBatis.dao;

import java.util.List;
import myBatis.model.Guide;
import org.mybatis.cdi.Mapper;

@Mapper
public interface GuideMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.GUIDE
     *
     * @mbg.generated Mon Apr 20 22:49:37 EEST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.GUIDE
     *
     * @mbg.generated Mon Apr 20 22:49:37 EEST 2020
     */
    int insert(Guide record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.GUIDE
     *
     * @mbg.generated Mon Apr 20 22:49:37 EEST 2020
     */
    Guide selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.GUIDE
     *
     * @mbg.generated Mon Apr 20 22:49:37 EEST 2020
     */
    List<Guide> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.GUIDE
     *
     * @mbg.generated Mon Apr 20 22:49:37 EEST 2020
     */
    int updateByPrimaryKey(Guide record);
}