package myBatis.dao;

import java.util.List;
import myBatis.model.Trip;
import org.mybatis.cdi.Mapper;

@Mapper
public interface TripMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TRIP
     *
     * @mbg.generated Mon Apr 20 22:49:37 EEST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TRIP
     *
     * @mbg.generated Mon Apr 20 22:49:37 EEST 2020
     */
    int insert(Trip record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TRIP
     *
     * @mbg.generated Mon Apr 20 22:49:37 EEST 2020
     */
    Trip selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TRIP
     *
     * @mbg.generated Mon Apr 20 22:49:37 EEST 2020
     */
    List<Trip> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TRIP
     *
     * @mbg.generated Mon Apr 20 22:49:37 EEST 2020
     */
    int updateByPrimaryKey(Trip record);
}