package myBatis.model;

public class Trip {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.TRIP.ID
     *
     * @mbg.generated Mon Apr 20 22:49:37 EEST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.TRIP.NAME
     *
     * @mbg.generated Mon Apr 20 22:49:37 EEST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.TRIP.GUIDE_ID
     *
     * @mbg.generated Mon Apr 20 22:49:37 EEST 2020
     */
    private Integer guideId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.TRIP.ID
     *
     * @return the value of PUBLIC.TRIP.ID
     *
     * @mbg.generated Mon Apr 20 22:49:37 EEST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.TRIP.ID
     *
     * @param id the value for PUBLIC.TRIP.ID
     *
     * @mbg.generated Mon Apr 20 22:49:37 EEST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.TRIP.NAME
     *
     * @return the value of PUBLIC.TRIP.NAME
     *
     * @mbg.generated Mon Apr 20 22:49:37 EEST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.TRIP.NAME
     *
     * @param name the value for PUBLIC.TRIP.NAME
     *
     * @mbg.generated Mon Apr 20 22:49:37 EEST 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.TRIP.GUIDE_ID
     *
     * @return the value of PUBLIC.TRIP.GUIDE_ID
     *
     * @mbg.generated Mon Apr 20 22:49:37 EEST 2020
     */
    public Integer getGuideId() {
        return guideId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.TRIP.GUIDE_ID
     *
     * @param guideId the value for PUBLIC.TRIP.GUIDE_ID
     *
     * @mbg.generated Mon Apr 20 22:49:37 EEST 2020
     */
    public void setGuideId(Integer guideId) {
        this.guideId = guideId;
    }
}